#!/usr/bin/env bash

ffmpeg () {
	command ffmpeg -hide_banner "$@"
}

if [ "$1" ]
then
	ffmpeg -f s32le -i "$1" -ar 44100 -ac 1 -y tmp1.wav
	ffmpeg -f f32le -i tmp1.wav -y tmp2.wav
	ffmpeg -i tmp2.wav -f mp3 -y trolled.mp3
	rm tmp1.wav tmp2.wav
else
	echo "Usage: audiotroll <input file>"
fi

# das objekt stinkt
