#!/usr/bin/env bash

ffmpeg () {
	command ffmpeg -hide_banner "$@"
}

if [ "$1" ]
then
	ffmpeg -i "$1" -f s32le -ac 1 -y pipe:1 | \
	ffmpeg -f f32le -i pipe:0 -f wav -y pipe:1 | \
	ffmpeg -i pipe:0 -f mp3 -y trolled.mp3
else
	echo "Usage: audiotroll <input file>"
fi

# das objekt stinkt
